config/routes.rb
SimuladorBancario::Application.routes.draw do
  resources :payments

  resources :payment_plans

  resources :credit_lines do
    resources :payment_plans
  end

   root :to => 'CreditLines#index'

  get '/pyme/:id', to: 'welcome#index'

  get 'logins/login'
  post 'logins/authenticate'
  get 'logins/home'
  get 'logins/logout'

  get 'admins/new'
  post 'admins/create'
end

app/models/credit_line.rb
class CreditLine
  include Dynamoid::Document
  belongs_to :admin
  has_many :payment_plans
  
   index [ :admin_ids]

  field :name
  field :interest_rate, :float
  attr_accessible :interest_rate, :name
end

app/controllers/credit_lines_controller.rb
class CreditLinesController < ApplicationController

  before_filter :is_authenticated_user, :except => [:login, :authenticate]

  # GET /credit_lines
  # GET /credit_lines.json
  def index
    @adm = Admin.find(session[:user_id])
    puts "  qqqqqq" + @adm.id
    @array=[]
    @credit_lines = CreditLine.where(:admin_ids => @adm.id).all#all#@adm.credit_lines
    if @credit_lines.nil?
      @credit_lines.each do |credit_line|
        if credit_line.admin.id == session[:user_id]
        @array.push(credit_line)
        end
      end
    end

    puts(@credit_lines)
    puts(CreditLine.all)
    @array1 = PaymentPlan.all
    @payment_plans =[]
    @array1.each do |payment_plan|
      if payment_plan.admin.id == session[:user_id]
        @payment_plans.push(payment_plan)
      end
    end

    puts (@payment_plans.size)
    respond_to do |format|
      format.html # index.html.erb
      #format.json { render json: @credit_lines }
    end
  end

  # GET /credit_lines/1
  # GET /credit_lines/1.json
  def show
    @credit_line = CreditLine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @credit_line }
    end
  end

  # GET /credit_lines/new
  # GET /credit_lines/new.json
  def new
    @credit_line = CreditLine.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @credit_line }
    end
  end

  # GET /credit_lines/1/edit
  def edit
    @credit_line = CreditLine.find(params[:id])
  end

  # POST /credit_lines
  # POST /credit_lines.json
  def create
    @adm = Admin.find(session[:user_id])
    @credit_line = @adm.credit_lines.create(params[:credit_line])#CreditLine.new(params[:credit_line])
    respond_to do |format|
      if @credit_line
        format.html { redirect_to @credit_line, notice: 'Credit line was successfully created.' }
        format.json { render json: @credit_line, status: :created, location: @credit_line }
      else
        format.html { render action: "new" }
        format.json { render json: @credit_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /credit_lines/1
  # PUT /credit_lines/1.json
  def update
    @credit_line = CreditLine.find(params[:id])

    respond_to do |format|
      if @credit_line.update_attributes(params[:credit_line])
        format.html { redirect_to @credit_line, notice: 'Credit line was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @credit_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credit_lines/1
  # DELETE /credit_lines/1.json
  def destroy
    @credit_line = CreditLine.find(params[:id])
    @credit_line.destroy

    respond_to do |format|
      format.html { redirect_to credit_lines_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/credit_lines_helper.rb
module CreditLinesHelper
end

app/views/credit_lines/_form.html.erb
<%= form_for(@credit_line) do |f| %>
  <% if @credit_line.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@credit_line.errors.count, "error") %> prohibited this credit_line from being saved:</h2>

      <ul>
      <% @credit_line.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :interest_rate %><br />
    <%= f.text_field :interest_rate %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/credit_lines/edit.html.erb
<h1>Editing credit_line</h1>

<%= render 'form' %>

<%= link_to 'Show', @credit_line %> |
<%= link_to 'Back', credit_lines_path %>

app/views/credit_lines/index.html.erb
<h1>Listing All the Credit Lines</h1>

<table>
  <tr>
    <th>Interest rate</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @array.each do |credit_line| %>
  <tr>
    <td><%= credit_line.interest_rate%></td>
    <td><%= credit_line.name %></td>
    <td><%= link_to 'Show', credit_line %></td>
    <td><%= link_to 'Edit', edit_credit_line_path(credit_line) %></td>
    <td><%= link_to 'Destroy', credit_line, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<h1>Listing All the Payment Plans</h1>

<table>
  <tr>
    <th>Identification</th>
    <th>Numberofpayments</th>
    <th>Principal</th>
    <th>Risklevel</th>
    <th>State</th>
    <th>Creditline</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @payment_plans.each do |payment_plan| %>
      <tr>
        <td><%= payment_plan.identification %></td>
        <td><%= payment_plan.numberOfPayments %></td>
        <td><%= payment_plan.principal %></td>
        <td><%= payment_plan.riskLevel %></td>
        <td><%= payment_plan.state %></td>
        <% if payment_plan.creditLine.nil? %>
        <%else %>
        <td><%= CreditLine.find(payment_plan.creditLine.id).name%></td>
        <%end%>
        <td><%= link_to 'View Details', payment_plan %></td>
        <td><% link_to 'Edit', edit_payment_plan_path(payment_plan) %></td>
        <td><% link_to 'Destroy', payment_plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

<%= link_to 'New Credit line', new_credit_line_path %>
<br/>
<%= link_to 'Public url: /pyme/'.concat("#{@adm.pymeName}"), "/pyme/#{@adm.pymeName}" %>

app/views/credit_lines/new.html.erb
<h1>New credit_line</h1>

<%= render 'form' %>

<%= link_to 'Back', credit_lines_path %>

app/views/credit_lines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Interest rate:</b>
  <%= @credit_line.interest_rate %>
</p>

<p>
  <b>Name:</b>
  <%= @credit_line.name %>
</p>

<%= link_to 'Edit', edit_credit_line_path(@credit_line) %> |
<%= link_to 'Back', credit_lines_path %>