config/routes.rb
SimuladorBancario::Application.routes.draw do
  resources :payments

  resources :payment_plans

  resources :credit_lines do
    resources :payment_plans
  end

   root :to => 'CreditLines#index'

  get '/pyme/:id', to: 'welcome#index'

  get 'logins/login'
  post 'logins/authenticate'
  get 'logins/home'
  get 'logins/logout'

  get 'admins/new'
  post 'admins/create'
end

app/models/payment.rb
class Payment
  include Dynamoid::Document
  belongs_to :payment_plan
  attr_accessible :paymentAmortization, :paymentInterest, :paymentNumber, :pendingBalance, :totalPayment

  field :paymentAmortization, :float
  field :paymentInterest,:float
  field :paymentNumber,:integer
  field :pendingBalance, :float
  field :totalPayment, :float

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  # GET /payments
  # GET /payments.json
  def index
    tiempoInicial=Time.now
    t=PaymentPlan.find_by_state('In progress')

    t=PaymentPlan.where(:state=>'In progress').all
    puts(t.size)
    puts(PaymentPlan.where(:state=>'In progress'))

    if(t.nil?)
      puts('no enraaa')
    else
      credit=CreditLine.find(t.creditLine.id)
      puts(credit.name)
      cuotaAmortizacion=(t.principal/t.numberOfPayments)
      capitalVivo=t.principal #-AMORTIZACION
      interes=capitalVivo*(credit.interest_rate/100)
      #payment=t.payments.create(paymentNumber: 0, paymentInterest: 0, paymentAmortization: 0, pendingBalance: capitalVivo, totalPayment:0)
      payment.save
      cont=0
      totalPagado=0
      capitalVivo=t.principal
      puts(t.numberOfPayments)
      while cont.to_i < t.numberOfPayments
        cont= cont.to_i+1
        puts(cont)

        capitalVivo=capitalVivo-cuotaAmortizacion
        interes=capitalVivo*(credit.interest_rate/100)
        amort=cuotaAmortizacion + interes.abs
        totalPagado=totalPagado+(amort.abs)
        #payment=t.payments.create(paymentNumber: cont, paymentInterest: interes, paymentAmortization: cuotaAmortizacion, pendingBalance: capitalVivo, totalPayment:totalPagado)
        payment.save
      end
      puts"guardooo"
      risk=0
      while (Time.now.sec - tiempoInicial.sec<25)
        risk=rand(10)
      end
      puts(risk)
      t.update_attribute(:riskLevel,risk)

      t.update_attribute(:state, 'Completed')
      t.save
    end

    #------------
    @payments = Payment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @payments }
    end
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
    @payment = Payment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @payment }
    end
  end

  # GET /payments/new
  # GET /payments/new.json
  def new
    @payment = Payment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @payment }
    end
  end

  # GET /payments/1/edit
  def edit
    @payment = Payment.find(params[:id])
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(params[:payment])

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render json: @payment, status: :created, location: @payment }
      else
        format.html { render action: "new" }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /payments/1
  # PUT /payments/1.json
  def update
    @payment = Payment.find(params[:id])

    respond_to do |format|
      if @payment.update_attributes(params[:payment])
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment = Payment.find(params[:id])
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :paymentAmortization %><br />
    <%= f.text_field :paymentAmortization %>
  </div>
  <div class="field">
    <%= f.label :paymentInterest %><br />
    <%= f.text_field :paymentInterest %>
  </div>
  <div class="field">
    <%= f.label :paymentNumber %><br />
    <%= f.text_field :paymentNumber %>
  </div>
  <div class="field">
    <%= f.label :pendingBalance %><br />
    <%= f.text_field :pendingBalance %>
  </div>
  <div class="field">
    <%= f.label :totalPayment %><br />
    <%= f.text_field :totalPayment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<h1>Listing payments</h1>

<table>
  <tr>
    <th>Paymentamortization</th>
    <th>Paymentinterest</th>
    <th>Paymentnumber</th>
    <th>Pendingbalance</th>
    <th>Totalpayment</th>
    <th>Payment plan</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @payments.each do |payment| %>
  <tr>
    <td><%= payment.paymentAmortization %></td>
    <td><%= payment.paymentInterest %></td>
    <td><%= payment.paymentNumber %></td>
    <td><%= payment.pendingBalance %></td>
    <td><%= payment.totalPayment %></td>
    <td><%= payment.payment_plan %></td>
    <td><%= link_to 'Show', payment %></td>
    <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
    <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New payment</h1>

<%= render 'form' %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Paymentamortization:</b>
  <%= @payment.paymentAmortization %>
</p>

<p>
  <b>Paymentinterest:</b>
  <%= @payment.paymentInterest %>
</p>

<p>
  <b>Paymentnumber:</b>
  <%= @payment.paymentNumber %>
</p>

<p>
  <b>Pendingbalance:</b>
  <%= @payment.pendingBalance %>
</p>

<p>
  <b>Totalpayment:</b>
  <%= @payment.totalPayment %>
</p>

<p>
  <b>Payment plan:</b>
  <%= @payment.payment_plan %>
</p>


<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>