config/routes.rb
SimuladorBancario::Application.routes.draw do
  resources :payments

  resources :payment_plans

  resources :credit_lines do
    resources :payment_plans
  end

   root :to => 'CreditLines#index'

  get '/pyme/:id', to: 'welcome#index'

  get 'logins/login'
  post 'logins/authenticate'
  get 'logins/home'
  get 'logins/logout'

  get 'admins/new'
  post 'admins/create'
end

app/models/payment_plan.rb
class PaymentPlan
  include Dynamoid::Document
  has_many :payments
  belongs_to :admin
  belongs_to :creditLine

  field :birthdate, :datetime
  field :identification
  field :numberOfPayments, :integer
  field :principal, :float
  field :riskLevel, :integer
  field :state
  attr_accessible :birthdate, :identification, :numberOfPayments, :principal, :riskLevel, :state
end

app/controllers/payment_plans_controller.rb
class PaymentPlansController < ApplicationController
  # GET /payment_plans
  # GET /payment_plans.json
  def index
    @payment_plans = PaymentPlan.all

    @payment_plans.each do |payment_plan|
      puts(payment_plan.creditLine)
      puts(payment_plan.creditLine.id)
      puts(CreditLine.find(payment_plan.creditLine.id))
      puts(CreditLine.find(payment_plan.creditLine.id).name)

    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @payment_plans }
    end
  end

  # GET /payment_plans/1
  # GET /payment_plans/1.json
  def show
    @payment_plan = PaymentPlan.find(params[:id])
    @payments= @payment_plan.payments.sort_by { |e|e[:numberOfPayments]}

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @payment_plan }
    end
  end

  # GET /payment_plans/new
  # GET /payment_plans/new.json
  def new
    @payment_plan = PaymentPlan.new

    @credit_lines=CreditLine.all
    puts(@creditLines)
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @payment_plan }
    end
  end

  # GET /payment_plans/1/edit
  def edit
    @payment_plan = PaymentPlan.find(params[:id])
  end

  # POST /payment_plans
  # POST /payment_plans.json
  def create
    puts('entro a crear')
    puts(params[:payment_plan][:creditLine])
    @creditLines= CreditLine.all()
    puts(params[:payment_plan][:birthDate])
    @credit=CreditLine.find(params[:payment_plan][:creditLine])

    par=params[:payment_plan]
    puts("ver la fecha")
    puts(par)
    puts(par["birthdate(1i)"].to_i)
    #date = DateTime.new(par["birthdate(1i)"].to_i, par["birthDate(2i)"].to_i, par["birthDate(3i)"].to_i)
    date=Time.zone.now
    @adm = Admin.find(session[:user_id])

    $i = 1
    $num = 50
    @array=[]
    while $i < $num  do
      @payment_plan = @adm.payment_plans.create(identification: par[:identification], numberOfPayments: par[:numberOfPayments], principal: par[:principal], riskLevel: par[:riskLevel], state: par[:state],creditLine:@credit, state: 'In progress')
      @array.push(@payment_plan)
      $i +=1
    end
    #@payment_plan = @adm.payment_plans.create(identification: par[:identification], numberOfPayments: par[:numberOfPayments], principal: par[:principal], riskLevel: par[:riskLevel], state: par[:state],creditLine:@credit, state: 'In progress')

   # @payment_plan.identification = par[:identification]
    puts(@credit.payment_plans.size)
    puts(PaymentPlan.all.size)
    puts(@payment_plan.id)

    #-------------------
    require 'yaml'
    require 'aws-sdk'

    config_file = File.join(File.dirname(__FILE__),"config.yml")
    config = YAML.load(File.read(config_file))
    AWS.config(config)

    queue_name ='PaymentPlansQueue'
    sqs = AWS::SQS.new
    puts "Creating queue '#{queue_name}' ..."
    q = nil
    begin
      # Creates new queue or gets existing queue
      q = sqs.queues.create queue_name
    rescue AWS::SQS::Errors::InvalidParameterValue => e
      puts "Invalid queue name '#{queue_name}'. "+e.message
      exit 1
    end
    puts "Waiting for queue created on AWS"
    loop do
      if q.exists?
        puts "Queue is created on AWS"
        break
      end
      sleep 1
    end
    @array.each do |plan|
       m = q.send_message plan.id
    end
    #-----------
    #@payment_plan.creditLine = @credit
    #@payment_plan.state = 'In progress'
    #puts(@credit.id)
    #puts(@payment_plan.creditLine.id)
    #puts(CreditLine.find(@payment_plan.creditLine.id).name)
    #puts('chap')

   # @payment_plan = PaymentPlan.new(params[:payment_plan])

    respond_to do |format|
      #if @payment_plan.save
        format.html { redirect_to @payment_plan, notice: 'Payment plan was successfully created.' }
        format.json { render json: @payment_plan, status: :created, location: @payment_plan }
      #else
        format.html { render action: "new" }
        format.json { render json: @payment_plan.errors, status: :unprocessable_entity }
      #end
    end
  end

  # PUT /payment_plans/1
  # PUT /payment_plans/1.json
  def update
    @payment_plan = PaymentPlan.find(params[:id])

    respond_to do |format|
      if @payment_plan.update_attributes(params[:payment_plan])
        format.html { redirect_to @payment_plan, notice: 'Payment plan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @payment_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_plans/1
  # DELETE /payment_plans/1.json
  def destroy
    @payment_plan = PaymentPlan.find(params[:id])
    @payment_plan.destroy

    respond_to do |format|
      format.html { redirect_to payment_plans_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/payment_plans_helper.rb
module PaymentPlansHelper
end

app/views/payment_plans/_form.html.erb
<%= form_for(@payment_plan) do |f| %>
  <% if @payment_plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment_plan.errors.count, "error") %> prohibited this payment_plan from being saved:</h2>

      <ul>
      <% @payment_plan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :birthdate %><br />
    <%= f.date_select :birthdate %>
  </div>
  <div class="field">
    <%= f.label :identification %><br />
    <%= f.text_field :identification %>
  </div>
  <div class="field">
    <%= f.label :numberOfPayments %><br />
    <%= f.number_field :numberOfPayments %>
  </div>
  <div class="field">
    <%= f.label :principal %><br />
    <%= f.text_field :principal %>
  </div>
  <div class="field">
    <%= f.label :creditLine %><br />
    <%= f.select :creditLine, options_from_collection_for_select(@creditLines,"id","name") %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payment_plans/edit.html.erb
<h1>Editing payment_plan</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment_plan %> |
<%= link_to 'Back', payment_plans_path %>

app/views/payment_plans/index.html.erb
<h1>Listing payment_plans</h1>

<table>
  <tr>
    <th>Birthdate</th>
    <th>Identification</th>
    <th>Numberofpayments</th>
    <th>Principal</th>
    <th>Risklevel</th>
    <th>State</th>
    <th>Creditline</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @payment_plans.each do |payment_plan| %>
  <tr>
    <td><%= payment_plan.birthdate %></td>
    <td><%= payment_plan.identification %></td>
    <td><%= payment_plan.numberOfPayments %></td>
    <td><%= payment_plan.principal %></td>
    <td><%= payment_plan.riskLevel %></td>
    <td><%= payment_plan.state %></td>
    <td><%= CreditLine.find(payment_plan.creditLine.id).name%></td>
    <td><%= link_to 'Show', payment_plan %></td>
    <td><%= link_to 'Edit', edit_payment_plan_path(payment_plan) %></td>
    <td><%= link_to 'Destroy', payment_plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Payment plan', new_payment_plan_path %>

app/views/payment_plans/new.html.erb
<h1>New payment_plan</h1>

<%= render 'form' %>

<%= link_to 'Back', payment_plans_path %>

app/views/payment_plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Identification:</b>
  <%= @payment_plan.identification %>
</p>

<p>
  <b>Numberofpayments:</b>
  <%= @payment_plan.numberOfPayments %>
</p>

<p>
  <b>Principal:</b>
  <%= @payment_plan.principal %>
</p>

<p>
  <b>Risklevel:</b>
  <%= @payment_plan.riskLevel %>
</p>

<p>
  <b>State:</b>
  <%= @payment_plan.state %>
</p>

<p>
  <b>Creditline:</b>
  <% @payment_plan.creditLine %>
<td><%= CreditLine.find(@payment_plan.creditLine.id).name%></td>
</p>


<% if @payment_plan.state !='In progress'%>
    <!-- Se Pintan los planes de pagos-->

    <h1>Listing payments</h1>

    <table>
      <tr>
        <th>Paymentnumber</th>
        <th>Paymentinterest</th>
        <th>Paymentamortization</th>
        <th>Pendingbalance</th>
        <th>Totalpayment</th>
      </tr>

      <% @payments.each do |payment| %>
          <tr>
            <td><%= payment.paymentNumber %></td>
            <td><%= payment.paymentInterest %></td>
            <td><%= payment.paymentAmortization %></td>
            <td><%= payment.pendingBalance %></td>
            <td><%= payment.totalPayment %></td>
          </tr>
      <% end %>
    </table>

    <br />

    <%= link_to 'Back', :back %>

<% else%>
    <p>
      <b>Message:</b>
      Your payment plan is in process, please wait
    </p>
    <%= link_to 'Refresh', @payment_plan %>
<% end%>









<%= link_to 'Edit', edit_payment_plan_path(@payment_plan) %> |
<%= link_to 'Back', payment_plans_path %>